### ISSUE TITLE
Is it possible to deploy on Netlify? 

### ISSUE THREAD

**Issue by rashidpathiyil** [prismicio-community/nuxt-starter-prismic-blog#6]
It's navigation not working with nuxt js generate.
It's showing 404 not found when trying to navigate pages.

**Comment by phillysnow** [comment]
Hi @rashidpathiyil 

We have released a new plugin along with @jamespegg & the team @nuxt which will automatically generate the routes for your pages and allow previews to work on statically generated websites.
https://prismic-nuxt.js.org/

This version of the blog doesn't currently use this new updated plugin. But another project I have does https://github.com/phillysnow/nuxt-static-test.

We will be working to update this blog project to use the new plugin as soon as possible.
